import { useMemo, useState } from "react";
import { Archive, ArrowDown, ArrowUp, Check, ChevronDown, CloudOff, Edit3, ExternalLink, Folder, Grid2X2, Layers3, List, MoreHorizontal, Plus, Search, SlidersHorizontal, Trash2, WifiOff, X, Camera, Home, Compass, UserRound } from "lucide-react";
import "./Redesign.css";

type Filter = "All" | "Pokémon" | "Graded" | "Raw" | "For Sale" | "For Trade";
type Sort = "Value" | "Name" | "Recent" | "Quantity" | "Gain";
type Card = { id:number; name:string; set:string; no:string; value:number|null; cost:number; grade?:string; grader?:string; sale?:boolean; trade?:boolean; color:string; quantity:number; fresh:string };
const cards:Card[]=[
  {id:1,name:"Charizard ex",set:"Pokémon 151",no:"006/165",value:482.5,cost:220,grade:"10",grader:"PSA",sale:true,color:"#a64a2f",quantity:1,fresh:"2h ago"},
  {id:2,name:"Pikachu VMAX",set:"Vivid Voltage",no:"188/185",value:310,cost:165,grade:"9",grader:"PSA",trade:true,color:"#b58f29",quantity:1,fresh:"2h ago"},
  {id:3,name:"Gengar VMAX",set:"Fusion Strike",no:"271/264",value:196.25,cost:96,color:"#684b9a",quantity:2,fresh:"yesterday"},
  {id:4,name:"Blastoise ex",set:"151",no:"009/165",value:88,cost:75,grade:"9.5",grader:"CGC",color:"#257e93",quantity:1,fresh:"3d ago"},
  {id:5,name:"Umbreon VMAX",set:"Evolving Skies",no:"215/203",value:742,cost:410,grade:"10",grader:"PSA",sale:true,color:"#39445d",quantity:1,fresh:"2h ago"},
  {id:6,name:"Mew ex",set:"Paldean Fates",no:"232/091",value:126,cost:62,color:"#ad5f81",quantity:1,fresh:"5d ago"},
  {id:7,name:"Lugia V",set:"Silver Tempest",no:"186/195",value:null,cost:145,grade:"9",grader:"BGS",color:"#70634a",quantity:1,fresh:"pricing paused"},
  {id:8,name:"Rayquaza VMAX",set:"Evolving Skies",no:"218/203",value:388,cost:280,color:"#49746d",quantity:1,fresh:"4h ago"}
];
const filters:Filter[]=["All","Pokémon","Graded","Raw","For Sale","For Trade"];

function Art({card,small=false}:{card:Card;small?:boolean}){return <div className={`card-art ${small?"list-art":""}`} style={{background:card.color}}><div className="art-orb" style={{background:`radial-gradient(circle at 35% 30%,#f5e4b5,${card.color} 55%,#111 100%)`}}/><div className="art-name">{card.name.split(" ")[0]}</div><span className="card-no">{card.no}</span>{card.grade&&<span className={`grade ${card.grader==="BGS"?"gold":""}`}><b>{card.grader}</b>{card.grade}</span>}<div className="card-caption"><strong>{card.name}</strong><span>{card.set} · {card.no}</span></div></div>}
function BottomNav(){const items:[typeof Home,string][]=[[Home,"Home"],[Layers3,"Collection"],[Camera,"Scan"],[Compass,"Market"],[UserRound,"Profile"]];return <nav className="bottom-nav">{items.map(([Icon,label])=>label==="Scan"?<button className="nav-item scan" key={label} aria-label="Scan a card"><Icon size={22}/></button>:<button className={`nav-item ${label==="Collection"?"active":""}`} key={label}><Icon size={18}/><span>{label}</span></button>)}</nav>}

export function Redesign(){
  const [filter,setFilter]=useState<Filter>("All"); const [query,setQuery]=useState(""); const [search,setSearch]=useState(false); const [grid,setGrid]=useState(true); const [sort,setSort]=useState<Sort>("Value"); const [ascending,setAscending]=useState(false);
  const [panel,setPanel]=useState<"advanced"|"lists"|"sort"|null>(null); const [selection,setSelection]=useState(false); const [selected,setSelected]=useState<number[]>([]); const [saved,setSaved]=useState<number[]>([2]); const [visible,setVisible]=useState(6); const [offline,setOffline]=useState(true); const [notice,setNotice]=useState(true); const [selectedList,setSelectedList]=useState("All Collection"); const [advanced,setAdvanced]=useState(false);
  const results=useMemo(()=>cards.filter(c=>{const t=query.toLowerCase(); const match=!t||`${c.name} ${c.set} ${c.no}`.toLowerCase().includes(t); return match&&(filter==="All"||filter==="Pokémon"||filter==="Graded"&&!!c.grade||filter==="Raw"&&!c.grade||filter==="For Sale"&&!!c.sale||filter==="For Trade"&&!!c.trade)}).sort((a,b)=>{let n=sort==="Name"?a.name.localeCompare(b.name):sort==="Recent"?a.id-b.id:sort==="Quantity"?a.quantity-b.quantity:(a.value??-1)-(b.value??-1); return ascending?n:-n}),[filter,query,sort,ascending]);
  const shown=results.slice(0,visible); const choose=(id:number)=>setSelected(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]); const close=()=>setPanel(null);
  const money=(v:number|null)=>v===null?"VALUE UNAVAILABLE":`AUD ${v.toLocaleString("en-AU",{minimumFractionDigits:2})}`;
  return <main className="vault-page"><div className="vault-frame">
    {offline&&<div className="status"><CloudOff size={14}/><span>Offline — showing cached collection</span><button onClick={()=>setOffline(false)}>SIMULATE ONLINE</button></div>}
    {notice&&<div className="error"><WifiOff size={16}/><span>Unable to refresh prices. Showing your last saved collection.<button onClick={()=>setNotice(false)}>Retry</button></span><button aria-label="Dismiss" onClick={()=>setNotice(false)}><X size={14}/></button></div>}
    <header className="vault-head"><div><div className="vault-kicker">Verified TCG · private archive</div><h1 className="vault-title">YOUR COLLECTION</h1></div><div className="head-actions"><button className="icon-btn" aria-label="Search collection" onClick={()=>setSearch(!search)}>{search?<X size={17}/>:<Search size={17}/>}</button><button className="icon-btn" aria-label="Collection archive"><Archive size={17}/></button><button className="icon-btn" aria-label="Add a card"><Plus size={18}/></button></div></header>
    {search&&<div className="search"><Search size={15} color="#899294"/><input autoFocus value={query} onChange={e=>{setQuery(e.target.value);setVisible(6)}} placeholder="Search card, set or number"/><span>{results.length}</span></div>}
    <section className="worth"><div className="worth-label">Profile worth · last synced 2h ago</div><div className="worth-value">AUD 1,944.75</div><div className="worth-meta">↑ AUD 84.20 · +4.5% this month</div></section>
    <div className="library-head"><div><div className="library-title">LIBRARY</div><div className="library-count">{results.length} OF {cards.length} SHOWING · 8 HOLDINGS</div></div><div className="head-tools"><button className="small-btn" onClick={()=>{setSelection(!selection);setSelected([])}}>{selection?"Done":"Select"}</button><button className="small-btn" onClick={()=>setPanel("lists")}><Folder size={12} color="#ef4a57"/>{selectedList==="All Collection"?"All":selectedList}</button><button className="small-btn" onClick={()=>setPanel("sort")}><span style={{color:"#ef9da2"}}>↯</span>{sort}<ChevronDown size={11}/></button><div className="toggle"><button className={grid?"active":""} onClick={()=>setGrid(true)} aria-label="Grid view"><Grid2X2 size={13}/></button><button className={!grid?"active":""} onClick={()=>setGrid(false)} aria-label="List view"><List size={13}/></button></div></div></div>
    <div className="summary-line"><button className="advanced" onClick={()=>setPanel("advanced")}><SlidersHorizontal size={12}/>Advanced filters {advanced&&<Check size={11}/>}</button><span className="result-meta">{results.length} results · {ascending?"Ascending":"Descending"}</span></div>
    <div className="filter-scroll">{filters.map(f=><button key={f} className={`filter ${filter===f?"active":""}`} onClick={()=>{setFilter(f);setVisible(6)}}>{filter===f&&<Check size={11} style={{verticalAlign:"-2px"}}/>} {f}</button>)}</div>
    {results.length===0?<div className="empty"><Layers3 size={27}/><strong>No cards match this slice</strong><p>Try another filter or clear your search.</p><button onClick={()=>{setFilter("All");setQuery("")}}>Reset view</button></div>:grid?<div className="cards">{shown.map(card=><article className={`card-wrap ${selected.includes(card.id)?"selected":""}`} key={card.id} onClick={()=>selection&&choose(card.id)}><div style={{position:"relative"}}><Art card={card}/><button className={`save ${saved.includes(card.id)?"saved":""}`} onClick={e=>{e.stopPropagation();setSaved(s=>s.includes(card.id)?s.filter(x=>x!==card.id):[...s,card.id])}}>{saved.includes(card.id)?"SAVED":"SAVE"}</button></div><div className="card-foot"><span className="card-price">{money(card.value)}</span>{card.sale&&<span className="card-state">FOR SALE</span>}{card.trade&&<span className="card-state" style={{color:"#d8ae68"}}>TRADE</span>}</div><div className="card-sub"><span>Cost AUD {card.cost.toFixed(2)}</span><button className="view-card" onClick={()=>alert(`${card.name} · Card Passport`)}>View card <ExternalLink size={10}/></button></div></article>)}</div>:<div className="list">{shown.map(card=><article className={`list-card ${selected.includes(card.id)?"selected":""}`} key={card.id} onClick={()=>selection&&choose(card.id)}><Art card={card} small/><div className="list-info"><strong>{card.name}</strong><p>{card.set}</p><p>{card.no} · {card.grade?`${card.grader} ${card.grade}`:"Near Mint"}</p><span className="tag">{card.quantity} held · {card.fresh}</span></div><div className="list-value"><b>{money(card.value)}</b><div className="row-actions"><button onClick={e=>{e.stopPropagation();alert(`Selling ${card.name}`)}}>Sell</button><button aria-label={`Edit ${card.name}`} onClick={e=>{e.stopPropagation();alert(`Edit ${card.name}`)}}><Edit3 size={11}/></button></div></div></article>)}</div>}
    {visible<results.length?<button className="load-more" onClick={()=>setVisible(v=>v+4)}>Load more cards <ArrowDown size={12} style={{verticalAlign:"-2px"}}/></button>:<div className="all-loaded">All {results.length} cards loaded · pricing freshness varies</div>}
    </div><BottomNav/>
    {selection&&<div className="selection-bar"><button onClick={()=>{setSelection(false);setSelected([])}}>Cancel</button><b>{selected.length} selected</b><button className="sale" onClick={()=>alert("Marked selected cards for sale")}>Sell</button><button className="trade" onClick={()=>alert("Marked selected cards for trade")}>Trade</button><button onClick={()=>alert("Choose a collection list")}><Folder size={13}/></button><button onClick={()=>alert("Delete selected cards")}><Trash2 size={13}/></button></div>}
    {panel&&<div className="scrim" onClick={close}><section className="sheet" onClick={e=>e.stopPropagation()}><div className="sheet-head"><h2>{panel==="advanced"?"ADVANCED FILTERS":panel==="lists"?"COLLECTION LISTS":"SORT LIBRARY"}</h2><button className="close" onClick={close}><X size={18}/></button></div>
      {panel==="advanced"&&<><p style={{fontSize:11,color:"var(--muted)",marginTop:0}}>Tune the vault without losing the bigger picture.</p>{["Condition · Near Mint","Grading company · Any","Grade · Any","Value · Any range","Acquisition date · Any","Pricing · Fresh · 7 days"].map(x=><div className="sheet-row" key={x}><span>{x}</span><ChevronDown size={14} color="#899294"/></div>)}<button className="sheet-cta" onClick={()=>{setAdvanced(true);close()}}>Apply filters</button></>}
      {panel==="sort"&&<>{(["Value","Name","Recent","Quantity","Gain"] as Sort[]).map(x=><button className="sheet-row" style={{width:"100%",background:x===sort?"#3a2225":"transparent",color:"var(--ink)",border:0,textAlign:"left"}} key={x} onClick={()=>{setSort(x);close()}}><span>{x}</span>{sort===x&&<Check size={15} color="#ef4a57"/>}</button>)}<button className="sheet-row" style={{width:"100%",background:"none",color:"var(--muted)",border:0}} onClick={()=>setAscending(!ascending)}>{ascending?<ArrowUp size={14}/>:<ArrowDown size={14}/>}<span>{ascending?"Ascending":"Descending"}</span></button></>}
      {panel==="lists"&&<>{[["All Collection","8 cards · AUD 1,944.75"],["High Value","3 cards · AUD 1,534.50"],["Trade Binder","2 cards · AUD 506.25"]].map(([name,sub])=><button className={`list-choice ${selectedList===name?"selected-list":""}`} key={name} onClick={()=>{setSelectedList(name);close()}}><Folder size={16} color="#ef4a57"/><span><b>{name}</b><small>{sub}</small></span>{selectedList===name?<Check size={15}/>:<MoreHorizontal size={16} color="#899294"/>}</button>)}<button className="sheet-cta" style={{background:"transparent",border:"1px dashed #ef4a57",color:"#ef9da2"}} onClick={()=>alert("Create collection list")}> <Plus size={14} style={{verticalAlign:"-3px"}}/> Create collection list</button></>}
    </section></div>}
  </main>
}